version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: otus_password
    ports:
      - "55432:5432"
    volumes:
      - otus_postgresql_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - otus_rabbitmq_data:/var/lib/rabbitmq

volumes:
  otus_postgresql_data:
  otus_rabbitmq_data:
