version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: otus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: otus_password
    ports:
      - "55432:5432"
    volumes:
      - otus_postgresql_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  otus_postgresql_data:
